# Generated by Django 4.2.2 on 2023-07-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
