# Generated by Django 4.2.2 on 2023-07-11 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_visitor_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='date',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='time_in',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='time_out',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country_of_origin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='id_passport_nbr',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='organization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='surname',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('devices', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('card', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.card')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.visitor')),
            ],
        ),
    ]
