# Generated by Django 4.2.2 on 2023-07-31 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.card'),
        ),
    ]
