# Generated by Django 4.2.2 on 2023-08-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'Approved Visitor'), ('CHECKOUT', 'Check Out Visitor'), ('DECLINE', 'Declined Visitor')], max_length=20),
        ),
    ]
