# Generated by Django 4.2.2 on 2023-08-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_alter_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('APPROVE', 'Approved Visitor'), ('CHECKOUT', 'Check Out Visitor'), ('DECLINE', 'Declined Visitor'), ('RECORD', 'Recorded a Visitor')], max_length=20),
        ),
    ]
