# Generated by Django 4.2.2 on 2023-08-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_waitinglist_user_requested'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitinglist',
            name='user_requested',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
