# Generated by Django 4.2.2 on 2023-08-06 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0016_remove_visitor_user_checked_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='devices',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='reason_for_decline',
        ),
        migrations.AddField(
            model_name='visitor',
            name='user_checked_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitor',
            name='user_saved',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_visitors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='country_of_origin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='organization',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
